import type { TestCase } from "./types";

export const testCases: TestCase[] = [
  {
    id: "alg-1",
    category: "algebra",
    difficulty: "easy",
    latex1: "x+1",
    latex2: "1+x",
    expectedEqual: true,
    description: "덧셈 교환법칙",
  },
  {
    id: "alg-2",
    category: "algebra",
    difficulty: "easy",
    latex1: "2x",
    latex2: "x+x",
    expectedEqual: true,
    description: "곱셈 분배",
  },
  {
    id: "alg-3",
    category: "algebra",
    difficulty: "easy",
    latex1: "\\frac{x}{1}",
    latex2: "x",
    expectedEqual: true,
    description: "1로 나누기",
  },
  {
    id: "alg-4",
    category: "algebra",
    difficulty: "easy",
    latex1: "x+1",
    latex2: "x+2",
    expectedEqual: false,
    description: "다른 수식 (비동등)",
  },
  {
    id: "alg-5",
    category: "algebra",
    difficulty: "medium",
    latex1: "(x+1)^2",
    latex2: "x^2+2x+1",
    expectedEqual: true,
    description: "완전제곱 전개",
  },
  {
    id: "alg-6",
    category: "algebra",
    difficulty: "medium",
    latex1: "\\frac{x^2-1}{x-1}",
    latex2: "x+1",
    expectedEqual: true,
    description: "인수분해 약분",
  },
  {
    id: "alg-7",
    category: "algebra",
    difficulty: "medium",
    latex1: "\\frac{1}{x}+\\frac{1}{y}",
    latex2: "\\frac{x+y}{xy}",
    expectedEqual: true,
    description: "분수 덧셈 통분",
  },
  {
    id: "trig-1",
    category: "trigonometry",
    difficulty: "medium",
    latex1: "\\sin^2(x)+\\cos^2(x)",
    latex2: "1",
    expectedEqual: true,
    description: "피타고라스 항등식",
  },
  {
    id: "trig-2",
    category: "trigonometry",
    difficulty: "medium",
    latex1: "\\tan(x)",
    latex2: "\\frac{\\sin(x)}{\\cos(x)}",
    expectedEqual: true,
    description: "탄젠트 정의",
  },
  {
    id: "trig-3",
    category: "trigonometry",
    difficulty: "medium",
    latex1: "\\sin(2x)",
    latex2: "2\\sin(x)\\cos(x)",
    expectedEqual: true,
    description: "배각 공식",
  },
  {
    id: "exp-1",
    category: "exponential",
    difficulty: "hard",
    latex1: "e^{i\\pi}+1",
    latex2: "0",
    expectedEqual: true,
    description: "오일러 공식",
  },
  {
    id: "exp-2",
    category: "exponential",
    difficulty: "medium",
    latex1: "\\ln(e^x)",
    latex2: "x",
    expectedEqual: true,
    description: "로그-지수 역함수",
  },
  {
    id: "exp-3",
    category: "exponential",
    difficulty: "medium",
    latex1: "e^{\\ln(x)}",
    latex2: "x",
    expectedEqual: true,
    description: "지수-로그 역함수",
  },
  {
    id: "calc-1",
    category: "calculus",
    difficulty: "medium",
    latex1: "\\frac{d}{dx}x^2",
    latex2: "2x",
    expectedEqual: true,
    description: "다항식 미분",
  },
  {
    id: "calc-2",
    category: "calculus",
    difficulty: "medium",
    latex1: "\\frac{d}{dx}\\sin(x)",
    latex2: "\\cos(x)",
    expectedEqual: true,
    description: "사인 미분",
  },
  {
    id: "calc-3",
    category: "calculus",
    difficulty: "medium",
    latex1: "\\frac{d}{dx}e^x",
    latex2: "e^x",
    expectedEqual: true,
    description: "지수함수 미분",
  },
  {
    id: "calc-4",
    category: "calculus",
    difficulty: "hard",
    latex1: "\\int_0^1 x \\, dx",
    latex2: "\\frac{1}{2}",
    expectedEqual: true,
    description: "정적분",
  },
  {
    id: "calc-5",
    category: "calculus",
    difficulty: "hard",
    latex1: "\\lim_{x \\to 0}\\frac{\\sin(x)}{x}",
    latex2: "1",
    expectedEqual: true,
    description: "삼각함수 극한",
  },
  {
    id: "calc-6",
    category: "calculus",
    difficulty: "hard",
    latex1: "\\lim_{x \\to \\infty}\\frac{1}{x}",
    latex2: "0",
    expectedEqual: true,
    description: "무한대 극한",
  },
];

export const categoryLabels: Record<TestCase["category"], string> = {
  algebra: "대수학",
  trigonometry: "삼각함수",
  exponential: "지수/로그",
  calculus: "미적분",
};

export const difficultyLabels: Record<TestCase["difficulty"], string> = {
  easy: "쉬움",
  medium: "보통",
  hard: "어려움",
};
